name = "v2ray-config-bot"
compatibility_date = "2023-08-01"
workers_dev = true
main = "src/worker.js"

[vars]
CF_API_KEY = "5fae9fcb9c193ce65de4b57689a94938b708e"
CF_ACCOUNT_ID = "e9930d5ca683b0461f73477050fee0c7"
CF_ZONE_ID = "80423e7547d2fa85e13796a1f41deced"
CF_API_EMAIL = "ambebalong@gmail.com"
SERVICE_NAME = "siren"
rootDomain = "joss.checker-ip.xyz"
ownerId  = "1467883032"

