name = "telegram-wildcard-bot"
type = "javascript"

# Kosongkan kalau deploy ke environment production via GitHub Actions
account_id = ""
workers_dev = true
main = "src/worker.js"
compatibility_date = "2025-06-01"

[env.production]
account_id = ""       # kosongkan, akan diisi dari workflow
zone_id = ""          # kosongkan, akan diisi dari workflow
route = "https://${ROOT_DOMAIN}/*"
vars = {}             # kosongkan, variabel diset lewat workflow

[triggers]
crons = []

[build]
command = "npm install"
