name = "v2ray-config-bot"
main = "src/worker.js"
compatibility_date = "2023-08-01"
account_id = "e9930d5ca683b0461f73477050fee0c7"
workers_dev = true

# Jangan taruh token rahasia di sini. Gunakan secret Wrangler via CLI atau Dashboard
