name = "v2ray-config-bot"
compatibility_date = "2023-08-01"
account_id = "e9930d5ca683b0461f73477050fee0c7"  # Replace with your Cloudflare account ID
workers_dev = true
main = "src/worker.js"

[vars]
TELEGRAM_BOT_TOKEN = "7626291818:AAG7dEWhfWZ4u8j9i7JWQ71vzNpz9h7UZq1"  # Will be overridden by GitHub Secrets
