name = "telegram-bot-worker"
type = "javascript"
account_id = "${ACCOUNT_ID}"
workers_dev = true
compatibility_date = "2025-06-01"

[env.production]
route = "" # kosong jika deploy workers.dev
zone_id = "${ZONE_ID}"

[build]
command = "npm install"
