name = "v2ray-config-bot"
compatibility_date = "2023-08-01"
workers_dev = true
main = "src/worker.js"

[vars]
ACCOUNT_ID = "e9930d5ca683b0461f73477050fee0c7"
ZONE_ID = "80423e7547d2fa85e13796a1f41deced"
API_EMAIL = "ambebalong@gmail.com"
SERVICE_NAME = "siren"
ROOT_DOMAIN = "joss.checker-ip.xyz"
OWNER_ID = "1467883032"
