name = "telegram-wildcard-bot"
main = "src/worker.js"
compatibility_date = "2025-06-01"
workers_dev = true

[env.production]
route = "https://${ROOT_DOMAIN}/*"
zone_id = "${ZONE_ID}"

[vars]
API_KEY = "${API_KEY}"
ACCOUNT_ID = "${ACCOUNT_ID}"
ZONE_ID = "${ZONE_ID}"
API_EMAIL = "${API_EMAIL}"
SERVICE_NAME = "${SERVICE_NAME}"
ROOT_DOMAIN = "${ROOT_DOMAIN}"
TELEGRAM_TOKEN = "${TELEGRAM_TOKEN}"
OWNER_ID = "${OWNER_ID}"

[build]
command = "npm install"
