name = "v2ray-config-bot"
compatibility_date = "2023-08-01"
workers_dev = true
main = "src/worker.js"

[vars]
API_KEY = ""
API_EMAIL = ""
ZONE_ID = ""
SERVICE_NAME = ""
ROOT_DOMAIN = ""
TELEGRAM_BOT_TOKEN = ""

[env.production]
[env.production.vars]
API_KEY = ""
API_EMAIL = ""
ZONE_ID = ""
SERVICE_NAME = ""
ROOT_DOMAIN = ""
TELEGRAM_BOT_TOKEN = ""
