name: Deploy VPN CF

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          environment: production
          workingDirectory: ./
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
          API_EMAIL: ${{ secrets.API_EMAIL }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          ROOT_DOMAIN: ${{ secrets.ROOT_DOMAIN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
