      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          environment: production
          workingDirectory: ./
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
          API_EMAIL: ${{ secrets.API_EMAIL }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          ROOT_DOMAIN: ${{ secrets.ROOT_DOMAIN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}

      - name: Debug Wrangler Version
        run: npx wrangler --version

      - name: Debug Node Version
        run: node --version

      - name: List files
        run: ls -la src
